### ISSUE TITLE
[DOC] Second or First order Derivative 

### ISSUE THREAD

**Issue by vhuber** [josephcslater/mousai#17]
In https://josephcslater.github.io/mousai/tutorial/demos/Theory_and_Examples.html
Do you use \ddot{z} or \dot{z} ?

![2019-04-19_9-16-16](https://user-images.githubusercontent.com/2920150/56412243-cfea7e00-6283-11e9-80f0-da0d7d5b4405.png)

VS 

![2019-04-19_9-16-47](https://user-images.githubusercontent.com/2920150/56412272-e2fd4e00-6283-11e9-9a84-9cdf06450c6c.png)

**Comment by josephcslater** [comment]
Yes. It depends on the code. I have one for each. There are multiple notebooks showing each being used.

**Comment by josephcslater** [comment]
Did you find the variable `eqform='second_order'`? You can set it to first order or second order form.

**Comment by josephcslater** [comment]
Answer is documented.
